"""empty message

Revision ID: 10c3b82d669b
Revises: 
Create Date: 2024-10-12 01:07:15.086119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c3b82d669b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=120), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('zip_code', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sauce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_spicy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tortilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_gmo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vegetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('salt', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('profile_image_url', sa.String(length=360), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('order_datetime', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tortilla_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tortilla_id'], ['tortilla.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protein_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('protein_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['protein_id'], ['protein.id'], )
    )
    op.create_table('queso_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('cheese_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], )
    )
    op.create_table('sauce_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sauce_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['sauce_id'], ['sauce.id'], )
    )
    op.create_table('vegetable_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vegetable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['vegetable_id'], ['vegetable.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegetable_association')
    op.drop_table('sauce_association')
    op.drop_table('queso_association')
    op.drop_table('protein_association')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('vegetable')
    op.drop_table('tortilla')
    op.drop_table('sauce')
    op.drop_table('protein')
    op.drop_table('cheese')
    op.drop_table('address')
    # ### end Alembic commands ###
