"""empty message

Revision ID: 674576cd270f
Revises: 6afe31543776
Create Date: 2024-10-05 01:31:44.877183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674576cd270f'
down_revision = '6afe31543776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
