"""empty message

Revision ID: 6afe31543776
Revises: 5f85581213f5
Create Date: 2024-09-24 01:59:30.598547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afe31543776'
down_revision = '5f85581213f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queso_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('cheese_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cheese_id'], ['cheese.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], )
    )
    op.create_table('sauce_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sauce_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['sauce_id'], ['sauce.id'], )
    )
    op.create_table('vegetable_association',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vegetable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['vegetable_id'], ['vegetable.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegetable_association')
    op.drop_table('sauce_association')
    op.drop_table('queso_association')
    # ### end Alembic commands ###
